/* Paojai Living World v3 — presentation layer only. No production authority changes. */
document.title='Paojai Living World — Game Quality Preview v3';
const v3chip=document.querySelector('.simchip');if(v3chip)v3chip.textContent='SHADOW SIM v3';
pxy=function(p){const k=kind(p),seed=p.place_key||p.display_name_th||'place';const jx=(rnd(seed,'v3px')-.5)*(k==='res'?62:34),jy=(rnd(seed,'v3py')-.5)*(k==='res'?34:20);return{x:112+(Number(p.grid_x)||50)*11.45+jx,y:890-(Number(p.grid_y)||50)*7.42+jy}};
nxy=function(n){const seed=n.cell_key||`${n.cell_x}:${n.cell_y}`;return{x:108+n.cell_x*116+Math.sin(n.cell_y*1.31)*15+(rnd(seed,'v3nx')-.5)*17,y:862-n.cell_y*76+Math.sin(n.cell_x*1.17)*10+(rnd(seed,'v3ny')-.5)*13}};
const V3D={RESIDENTIAL:{x:165,y:555,w:1085,h:300,c:'d-res',label:'🏘️ Residential'},SOCIAL:{x:435,y:315,w:430,h:255,c:'d-social',label:'☕ Social'},KNOWLEDGE:{x:820,y:175,w:450,h:300,c:'d-learn',label:'📚 Knowledge & Research'},CREATIVE:{x:105,y:245,w:390,h:300,c:'d-creative',label:'🎨 Creative'},WELLNESS:{x:65,y:470,w:435,h:300,c:'d-wellness',label:'🌿 Wellness & Park'},PLAY:{x:930,y:415,w:395,h:300,c:'d-play',label:'🎮 Entertainment'},CIVIC:{x:505,y:430,w:445,h:270,c:'d-civic',label:'🏛️ Civic Core'}};
renderDistricts=function(){const root=$('#districts');root.innerHTML='';for(const d of Object.values(V3D)){const e=document.createElement('div');e.className='district '+d.c;e.dataset.label=d.label;e.style.cssText=`left:${d.x}px;top:${d.y}px;width:${d.w}px;height:${d.h}px`;root.append(e)}for(const p of [{x:585,y:462,w:245,h:145},{x:500,y:345,w:170,h:112},{x:980,y:480,w:165,h:105}]){const e=document.createElement('i');e.className='plaza';e.style.cssText=`left:${p.x}px;top:${p.y}px;width:${p.w}px;height:${p.h}px`;root.append(e)}$('#water').innerHTML='<i class="water" style="left:105px;top:604px;width:178px;height:96px"></i><i class="water" style="left:1035px;top:242px;width:128px;height:72px"></i>'};
renderDecor=function(){const root=$('#decor');root.innerHTML='';const seeds=[];for(const [name,d] of Object.entries(V3D)){const count=name==='WELLNESS'?34:name==='RESIDENTIAL'?28:name==='SOCIAL'?19:14;for(let i=0;i<count;i++){const x=d.x+28+rnd(name,i+'v3x')*(d.w-56),y=d.y+28+rnd(name,i+'v3y')*(d.h-56);let t='tree';if(name==='SOCIAL'&&i<7)t='table';else if(name==='CIVIC'&&i<7)t='lamp';else if(i%11===0)t='bench';else if(i%9===0)t='flower';seeds.push({t,x,y,k:name+':v3:'+i})}}for(const s of seeds){const e=document.createElement('i');e.className=s.t;if(s.t==='tree')e.style.setProperty('--leaf',`hsl(${106+Math.floor(rnd(s.k,'h')*37)} 36% ${41+Math.floor(rnd(s.k,'l')*14)}%)`);e.style.left=s.x+'px';e.style.top=s.y+'px';root.append(e)}for(let i=0;i<9;i++){const e=document.createElement('i');e.className='lamp';e.style.left=(520+i*88)+'px';e.style.top=(485+Math.sin(i*.9)*15)+'px';root.append(e)}};
experience=function(){const r=$('#view').getBoundingClientRect();cam.ts=Math.max(.70,Math.min(.88,r.width/560));cam.tx=r.width/2-700*cam.ts;cam.ty=r.height*.47-505*cam.ts;follow=null};
fit=function(){const r=$('#view').getBoundingClientRect();cam.ts=Math.min(r.width/1400,r.height/930)*1.32;cam.tx=(r.width-1400*cam.ts)/2;cam.ty=(r.height-930*cam.ts)/2-30;follow=null};
const crowdLayer=document.createElement('div');crowdLayer.id='crowds';crowdLayer.className='fx';const fxNode=$('#fx');if(fxNode&&fxNode.parentNode)fxNode.parentNode.insertBefore(crowdLayer,fxNode);let v3CrowdStamp=0;
function v3Crowds(ms){if(cam.s>=.86){crowdLayer.innerHTML='';return}if(ms-v3CrowdStamp<650)return;v3CrowdStamp=ms;const groups=new Map();for(const a of actors){if(a.route.length)continue;if(!groups.has(a.from))groups.set(a.from,[]);groups.get(a.from).push(a)}let html='';for(const [place,list] of groups){if(list.length<4||!P.has(place))continue;const z=pxy(P.get(place));html+=`<span class="crowd" style="left:${z.x}px;top:${z.y-45}px">👥 ${list.length}</span>`}crowdLayer.innerHTML=html}
function v3LOD(ms){const world=$('#world'),s=cam.s;world.classList.toggle('v3city',s<.86);world.classList.toggle('v3district',s>=.86&&s<1.22);world.classList.toggle('v3agent',s>=1.22);for(const a of actors){const e=actorEls.get(a.id);if(!e)continue;let show=true;if(a.t==='NPC'&&a.id!==follow&&a.id!==sel){if(s<.72)show=(hash(a.id)%4===0);else if(s<.86)show=(hash(a.id)%2===0)}e.style.display=show?'':'none'}v3Crowds(ms)}
const v3BaseTick=tick;tick=function(ms){v3BaseTick(ms);v3LOD(ms)};
const v3BaseShowCityInfo=showCityInfo;showCityInfo=function(){v3BaseShowCityInfo();const meta=$('#sm');if(meta)meta.textContent='Public-Safe FACT + Shadow Simulation · Visual Renderer v3'};
window.addEventListener('orientationchange',()=>setTimeout(experience,180));
