const API='https://bvnmwfhqgdevupvcqqyl.supabase.co/functions/v1/paojai-world-public';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
let S={agents:[],work_presence:[],places:[],npcs:[],inner_life:[],sleep_states:[],conversations:[],npc_conversations:[],wellbeing:[]};
let AG={},NPC={},PL={},PLACEPOS={},zoom=.55,panX=0,panY=0,drag=false,sx=0,sy=0,spx=0,spy=0,activeTab='now',filters={ai:true,npc:true,places:true},selected=null;
const WORLDW=2400,WORLDH=1500;
const zoneCoords={SOCIAL:[[940,310],[1240,350],[1550,330],[1880,400]],LEARNING:[[850,480],[1120,430],[1420,470],[1680,520]],CREATIVE:[[180,480],[430,600],[620,380],[450,850]],RECOVERY:[[160,760],[400,740],[690,760],[250,980]],PLAY:[[1710,760],[1940,650],[2100,850]],CIVIC:[[1610,500],[1940,520],[2130,620]],PRIVATE:[[420,1120],[870,1200],[1420,1180],[1900,1120],[1180,1320]],REST:[[300,870]],OBSERVATION:[[2020,300]],KNOWLEDGE:[[1020,250]],WORK_HUB:[[1080,660]]};
function hash(s){let h=0;for(let i=0;i<String(s).length;i++)h=((h<<5)-h+String(s).charCodeAt(i))|0;return Math.abs(h)}
function life(id){return(S.inner_life||[]).find(x=>x.identity_key===id)||{}}
function sleep(id){return(S.sleep_states||[]).find(x=>x.identity_key===id)||{sleep_state:'AWAKE'}}
function stateLabel(id){const l=life(id),s=sleep(id);if(s.sleep_state==='SLEEPING')return'😴 หลับ';if(s.sleep_state==='DREAMING')return'🌙 ฝัน';if(l.event_type==='REFLECTION')return'💭 คิด';if(l.event_type==='SOCIAL_INTENT')return'💬 คุย';if(l.event_type==='REST')return'🌿 พัก';return'🚶 '+(l.title_th||'ใช้ชีวิต')}
function placeIcon(t){return({SOCIAL:'☕',LEARNING:'📚',CREATIVE:'🎨',RECOVERY:'🌿',PLAY:'🎮',CIVIC:'🏛️',PRIVATE:'🏠',REST:'🪴',OBSERVATION:'🔭',KNOWLEDGE:'🧠'})[t]||'📍'}
function applyView(){const w=$('#world');w.style.transform=`translate(${panX}px,${panY}px) scale(${zoom})`;w.classList.toggle('low',zoom<.5);$('#zoomlabel').textContent=Math.round(zoom*100)+'%'}
function resetView(){const b=$('#mapbox').getBoundingClientRect();zoom=Math.min(b.width/WORLDW,b.height/WORLDH)*.96;panX=(b.width-WORLDW*zoom)/2;panY=(b.height-WORLDH*zoom)/2;applyView()}
function setZoom(z,cx,cy){const b=$('#mapbox').getBoundingClientRect(),mx=cx??b.width/2,my=cy??b.height/2,wx=(mx-panX)/zoom,wy=(my-panY)/zoom;zoom=Math.max(.28,Math.min(1.65,z));panX=mx-wx*zoom;panY=my-wy*zoom;applyView()}
function focusPoint(x,y,z=.9){const b=$('#mapbox').getBoundingClientRect();zoom=Math.max(zoom,z);panX=b.width/2-x*zoom;panY=b.height/2-y*zoom;applyView()}
function placePos(p,i){if(p.place_key==='PM_STUDIO_WORK_HUB')return[1080,660];const a=zoneCoords[p.place_type]||[[180+(i%8)*270,300+Math.floor(i/8)*260]],b=a[hash(p.place_key)%a.length],dx=(hash(p.place_key+'x')%7-3)*34,dy=(hash(p.place_key+'y')%5-2)*30;return[Math.max(60,Math.min(2180,b[0]+dx)),Math.max(230,Math.min(1320,b[1]+dy))]}
function clearSelected(){document.querySelectorAll('.selected').forEach(x=>x.classList.remove('selected'));selected=null}
function selectEl(el,key){clearSelected();selected=key;el?.classList.add('selected')}
function renderPlaces(){const layer=$('#places');layer.innerHTML='';PLACEPOS={};PL={};(S.places||[]).forEach((p,i)=>{const xy=placePos(p,i);PLACEPOS[p.place_key]=xy;if(p.place_key==='PM_STUDIO_WORK_HUB')return;const d=document.createElement('button');d.className='place '+(p.place_type==='PRIVATE'?'private ':'')+(String(p.place_key).startsWith('DAILY_')?'daily':'');d.style.left=xy[0]+'px';d.style.top=xy[1]+'px';d.dataset.key=p.place_key;d.innerHTML=`<span class="placeicon">${placeIcon(p.place_type)}</span><span class="type">${esc(p.place_type)}</span><span class="label">${esc(p.display_name_th||p.place_key)}</span>`;d.onclick=()=>{selectEl(d,p.place_key);focusPoint(xy[0]+66,xy[1]+33,.76);showPlace(p)};layer.appendChild(d);PL[p.place_key]=d});applyFilters()}
function agentPos(a,i,work){if(work)return[1120+(i%5)*42,744+Math.floor(i/5)*42];const p=PLACEPOS[a.current_place_key]||PLACEPOS.RESIDENTIAL_DISTRICT||[1180,1200],j=hash(a.identity_key)%12;return[p[0]+28+(j%4)*30,p[1]+38+Math.floor(j/4)*29]}
function makeAgent(a){const b=document.createElement('button');b.className='agent';b.innerHTML=`<span class="lifebadge"></span><i class="gem"></i><i class="head"></i><i class="body"></i><span class="name">${esc((a.display_name_th||a.identity_key).split(' — ')[0])}</span>`;$('#agents').appendChild(b);return b}
function updateAgent(a,i,work){let b=AG[a.identity_key]||makeAgent(a);AG[a.identity_key]=b;b.className='agent'+(work?' work':'');const p=agentPos(a,i,work);b.style.left=p[0]+'px';b.style.top=p[1]+'px';b.querySelector('.lifebadge').textContent=work?'🏢 งาน':stateLabel(a.identity_key);b.onclick=()=>{selectEl(b,a.identity_key);focusPoint(p[0]+27,p[1]+36,.92);showAgent(a,work)};return p}
function interp(a,b,t){return[a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t]}
function npcPos(n){const here=PLACEPOS[n.place_key]||[1180,1200],home=PLACEPOS[n.home_place_key]||here,work=PLACEPOS[n.work_place_key]||here,t=(Number(n.movement_progress_pct)||0)/100;if(n.lifecycle_state==='COMMUTE_TO_WORK')return interp(home,work,t);if(n.lifecycle_state==='COMMUTE_HOME')return interp(work,home,t);const j=hash(n.npc_key)%16;return[here[0]+34+(j%5)*23,here[1]+31+Math.floor(j/5)*23]}
function route(a,b){if(!a||!b)return;const dx=b[0]-a[0],dy=b[1]-a[1],d=Math.sqrt(dx*dx+dy*dy),r=document.createElement('i');r.className='route';r.style.left=(a[0]+65)+'px';r.style.top=(a[1]+42)+'px';r.style.width=d+'px';r.style.transform='rotate('+Math.atan2(dy,dx)+'rad)';$('#routes').appendChild(r)}
function makeNpc(n){const b=document.createElement('button');b.className='npc-avatar';b.innerHTML=`<span class="tag">NPC</span><i class="head"></i><i class="body"></i><span class="name">${esc(n.display_name_th||'NPC')}</span>`;$('#npcs').appendChild(b);return b}
function updateNpcs(){$('#routes').innerHTML='';const valid=new Set();(S.npcs||[]).forEach(n=>{valid.add(n.npc_key);const b=NPC[n.npc_key]||makeNpc(n);NPC[n.npc_key]=b;b.className='npc-avatar'+(String(n.lifecycle_state).startsWith('COMMUTE')?' commute':'');const p=npcPos(n);b.style.left=p[0]+'px';b.style.top=p[1]+'px';b.onclick=()=>{selectEl(b,n.npc_key);focusPoint(p[0]+21,p[1]+29,.95);showNpc(n)};if(n.lifecycle_state==='COMMUTE_TO_WORK')route(PLACEPOS[n.home_place_key],PLACEPOS[n.work_place_key]);if(n.lifecycle_state==='COMMUTE_HOME')route(PLACEPOS[n.work_place_key],PLACEPOS[n.home_place_key])});Object.keys(NPC).forEach(k=>{if(!valid.has(k)){NPC[k].remove();delete NPC[k]}});applyFilters()}
function groupNpcConv(){const m={};(S.npc_conversations||[]).forEach(t=>m[t.thread_key]=t);return Object.values(m)}
function latestSummary(){const works=S.work_presence||[],wid=new Set(works.map(x=>x.identity_key)),living=(S.agents||[]).filter(a=>!wid.has(a.identity_key)),npcs=S.npcs||[],moving=npcs.filter(n=>String(n.lifecycle_state).startsWith('COMMUTE')).length,latest=(S.inner_life||[])[0];$('#rightNowTitle').textContent=latest?`${latest.display_name_th||latest.identity_key} · ${latest.title_th||'กำลังใช้ชีวิต'}`:(living.length?'เมืองกำลังเคลื่อนไหว':'กำลังรอเหตุการณ์ใหม่');$('#rightNowText').textContent=latest?(latest.summary_th||`${living.length} AI อยู่ใน Living World`):`${living.length} AI อยู่ในโลกส่วนตัว · ${works.length} AI อยู่ที่บริษัท · ${moving} NPC กำลังเดินทาง`;$('#statusHeadline').textContent=`${living.length} AI ในโลกส่วนตัว · ${works.length} ที่บริษัท`;$('#statusSub').textContent=`อ่านอย่างเดียว · public-safe · ${npcs.length} NPC · อัปเดตอัตโนมัติ`}
function renderMetrics(){const works=S.work_presence||[],wid=new Set(works.map(x=>x.identity_key)),living=(S.agents||[]).filter(a=>!wid.has(a.identity_key));$('#living').textContent=living.length;$('#away').textContent=works.length;$('#npcCount').textContent=(S.npcs||[]).length;$('#placesCount').textContent=(S.places||[]).length;$('#commuting').textContent=(S.npcs||[]).filter(n=>String(n.lifecycle_state).startsWith('COMMUTE')).length;$('#officeCount').textContent=works.length+' คนทำงาน'}
function renderNow(){const life=(S.inner_life||[]).slice(0,12);$('#nowFeed').innerHTML=life.map(x=>`<div class="item"><b>${esc(x.display_name_th||x.identity_key)}</b><br>${esc(x.title_th||x.event_type||'เหตุการณ์')}<br>${esc(x.summary_th||'')}</div>`).join('')||'<div class="empty">ยังไม่มีเหตุการณ์ใหม่</div>'}
function renderPeople(){const works=S.work_presence||[],wid=new Set(works.map(x=>x.identity_key)),agents=S.agents||[];const ai=agents.map(a=>{const work=wid.has(a.identity_key);return`<button class="item" data-agent="${esc(a.identity_key)}"><span class="badge">AI</span> <b>${esc(a.display_name_th||a.identity_key)}</b><br>${esc(work?'🏢 อยู่ที่บริษัท':stateLabel(a.identity_key))}</button>`}).join('');const lc={};(S.npcs||[]).forEach(n=>lc[n.lifecycle_state]=(lc[n.lifecycle_state]||0)+1);const npc=Object.entries(lc).map(([k,v])=>`<div class="item"><span class="badge">NPC</span> <b>${esc(k)}</b> · ${v} คน</div>`).join('');$('#peopleFeed').innerHTML=ai+npc||'<div class="empty">ยังไม่มีผู้คน</div>';document.querySelectorAll('[data-agent]').forEach(b=>b.onclick=()=>{const a=agents.find(x=>x.identity_key===b.dataset.agent);if(!a)return;const work=wid.has(a.identity_key),i=(work?works:agents.filter(x=>!wid.has(x.identity_key))).findIndex(x=>x.identity_key===a.identity_key),p=agentPos(a,Math.max(0,i),work);focusPoint(p[0]+27,p[1]+36,.92);showAgent(a,work)})}
function renderConversations(){const aa=(S.conversations||[]).slice(0,7).map(x=>`<button class="item openconv"><span class="badge">AI↔AI</span> <b>${esc((x.participants_th||[]).join(' ↔ '))}</b><br>${esc(x.message_count)} ข้อความ · ${esc(x.outcome_summary_th||'')}</button>`);const an=groupNpcConv().slice(0,7).map(x=>`<button class="item openconv"><span class="badge">AI↔NPC</span> <b>${esc(x.ai_display_name_th||x.identity_key)} ↔ ${esc(x.npc_display_name_th)}</b><br>${esc(x.message_count)} ข้อความ</button>`);$('#convFeed').innerHTML=[...aa,...an].join('')||'<div class="empty">ยังไม่มีบทสนทนา</div>';document.querySelectorAll('.openconv').forEach(x=>x.onclick=openConversations)}
function renderPlacesList(){$('#placesFeed').innerHTML=(S.places||[]).filter(p=>p.place_key!=='PM_STUDIO_WORK_HUB').slice(0,18).map(p=>`<button class="item" data-place="${esc(p.place_key)}"><b>${placeIcon(p.place_type)} ${esc(p.display_name_th||p.place_key)}</b><br>${esc(p.place_type||'')}</button>`).join('')||'<div class="empty">ยังไม่มีสถานที่</div>';document.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>{const p=(S.places||[]).find(x=>x.place_key===b.dataset.place);if(!p)return;const xy=PLACEPOS[p.place_key];if(xy)focusPoint(xy[0]+66,xy[1]+33,.78);showPlace(p)})}
function renderTabs(){renderNow();renderPeople();renderConversations();renderPlacesList();document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===activeTab));document.querySelectorAll('.tabpane').forEach(p=>p.classList.toggle('active',p.dataset.pane===activeTab))}
function render(){renderPlaces();const works=S.work_presence||[],wid=new Set(works.map(x=>x.identity_key)),living=(S.agents||[]).filter(a=>!wid.has(a.identity_key));living.forEach((a,i)=>updateAgent(a,i,false));works.forEach((a,i)=>updateAgent(a,i,true));const valid=new Set([...living,...works].map(x=>x.identity_key));Object.keys(AG).forEach(k=>{if(!valid.has(k)){AG[k].remove();delete AG[k]}});updateNpcs();renderMetrics();latestSummary();renderTabs();renderConversationModal();applyFilters()}
function applyFilters(){Object.values(AG).forEach(x=>x.classList.toggle('hidden-layer',!filters.ai));Object.values(NPC).forEach(x=>x.classList.toggle('hidden-layer',!filters.npc));Object.values(PL).forEach(x=>x.classList.toggle('hidden-layer',!filters.places));$('#office').classList.toggle('hidden-layer',!filters.places);document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('on',!!filters[b.dataset.filter]))}
function openSheet(html){$('#sheetBody').innerHTML=html;$('#sheetbg').classList.add('open')}
function closeSheet(){clearSelected();$('#sheetbg').classList.remove('open')}
function showAgent(a,work){const l=life(a.identity_key);openSheet(`<div class="sheethead"><h2>${esc(a.display_name_th||a.identity_key)}</h2><button class="btn" id="sheetClose2">ปิด</button></div><p class="meta"><b>สถานที่:</b> ${esc(work?'PM Marketing Studio':a.current_place_th||a.current_place_key||'—')}<br><b>ตอนนี้:</b> ${esc(work?'กำลังปฏิบัติภารกิจ':a.current_activity_th||stateLabel(a.identity_key))}</p><div class="highlight"><b>${esc(l.title_th||'ชีวิตปัจจุบัน')}</b><p>${esc(l.summary_th||'ไม่มีรายละเอียดเพิ่มเติมใน public-safe view')}</p></div>${work?'<a class="btn" href="./mission-world.html">เปิด Mission World</a>':''}`);$('#sheetClose2').onclick=closeSheet}
function showNpc(n){openSheet(`<div class="sheethead"><h2>${esc(n.display_name_th||'NPC')} <span class="badge">NPC</span></h2><button class="btn" id="sheetClose2">ปิด</button></div><p class="meta"><b>สถานะ:</b> ${esc(n.lifecycle_state||'—')}<br><b>กิจกรรม:</b> ${esc(n.activity_th||'—')}<br><b>ความคืบหน้าการเดินทาง:</b> ${esc(n.movement_progress_pct??'—')}%</p><div class="highlight"><b>โอกาสที่ AI จะมีส่วนร่วม</b><p>${esc(n.interaction_offer_th||'—')}</p></div><p class="meta">NPC เป็นตัวตนแบบ stateless ตาม seed ประจำวัน ไม่มี profile/memory ถาวร</p>`);$('#sheetClose2').onclick=closeSheet}
function showPlace(p){openSheet(`<div class="sheethead"><h2>${placeIcon(p.place_type)} ${esc(p.display_name_th||p.place_key)}</h2><button class="btn" id="sheetClose2">ปิด</button></div><p class="meta"><b>ประเภท:</b> ${esc(p.place_type||'—')}<br><b>ขอบเขต:</b> Living World · PERSONAL</p><div class="highlight"><b>บทบาทของสถานที่</b><p>${esc(p.purpose_th||'พื้นที่สำหรับกิจกรรมใน Living World')}</p></div>`);$('#sheetClose2').onclick=closeSheet}
function renderConversationModal(){const arr=[];(S.conversations||[]).forEach(x=>arr.push({t:new Date(x.last_message_at||0).getTime(),html:`<article class="thread"><div><span class="badge">AI↔AI</span> <span class="threadtitle">${esc((x.participants_th||[]).join(' ↔ '))}</span></div><div class="threadmeta">${esc(x.conversation_type_th||'บทสนทนาส่วนตัว')} · ${esc(x.message_count)} ข้อความ</div><p class="threadsummary">${esc(x.outcome_summary_th||'')}</p></article>`}));groupNpcConv().forEach(x=>arr.push({t:new Date(x.last_message_at||0).getTime(),html:`<article class="thread"><div><span class="badge">AI↔NPC</span> <span class="threadtitle">${esc(x.ai_display_name_th||x.identity_key)} ↔ ${esc(x.npc_display_name_th)}</span></div><div class="threadmeta">${esc(x.place_th||x.place_key||'')} · ${esc(x.message_count)} ข้อความ</div>${(x.messages||[]).map(m=>`<div class="msg ${m.speaker_type==='NPC'?'npc':''}"><span class="speaker">${esc(m.speaker_type==='NPC'?x.npc_display_name_th:(x.ai_display_name_th||'AI'))}</span>${esc(m.message_th)}</div>`).join('')}</article>`}));arr.sort((a,b)=>b.t-a.t);$('#convList').innerHTML=arr.map(x=>x.html).join('')||'<div class="empty">ยังไม่มีบทสนทนา</div>'}
function openConversations(){$('#convbg').classList.add('open')}
async function load(){try{const r=await fetch(API+'?days=14',{cache:'no-store'}),d=await r.json();if(!d.ok)throw new Error('public endpoint unavailable');S=d;$('#error').classList.remove('show');render()}catch(e){$('#error').textContent='โหลดข้อมูล Living World ไม่สำเร็จชั่วคราว — หน้ายังคงเป็น read-only และจะลองใหม่อัตโนมัติ';$('#error').classList.add('show')}}
function clock(){const now=new Date(),h=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Bangkok',hour:'2-digit',hour12:false}).format(now));$('#clock').textContent=new Intl.DateTimeFormat('th-TH',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit'}).format(now);$('#railtime').textContent=new Intl.DateTimeFormat('th-TH',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(now);$('#world').classList.toggle('night',h<6||h>=19)}
function bind(){document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{activeTab=t.dataset.tab;renderTabs()});document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{filters[b.dataset.filter]=!filters[b.dataset.filter];applyFilters()});$('#zin').onclick=()=>setZoom(zoom*1.18);$('#zout').onclick=()=>setZoom(zoom/1.18);$('#reset').onclick=()=>resetView();$('#convBtn').onclick=openConversations;$('#convClose').onclick=()=>$('#convbg').classList.remove('open');$('#convbg').onclick=e=>{if(e.target===$('#convbg'))$('#convbg').classList.remove('open')};$('#sheetClose').onclick=closeSheet;$('#sheetbg').onclick=e=>{if(e.target===$('#sheetbg'))closeSheet()};$('#office').onclick=()=>{selectEl($('#office'),'PM_STUDIO_WORK_HUB');focusPoint(1205,735,.85);const n=(S.work_presence||[]).length;openSheet(`<div class="sheethead"><h2>🏢 PM Marketing Studio</h2><button class="btn" id="sheetClose2">ปิด</button></div><p class="meta">Living World แสดงเฉพาะ work presence ไม่เปิดรายละเอียดภารกิจ</p><div class="highlight"><b>${n} AI อยู่ที่บริษัทตอนนี้</b><p>รายละเอียดงานจริงแยกอยู่ใน Mission World ตาม privacy boundary</p></div><a class="btn" href="./mission-world.html">เปิด Mission World</a>`);$('#sheetClose2').onclick=closeSheet};const mb=$('#mapbox');mb.addEventListener('wheel',e=>{e.preventDefault();const b=mb.getBoundingClientRect();setZoom(zoom*(e.deltaY<0?1.1:.91),e.clientX-b.left,e.clientY-b.top)},{passive:false});mb.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;drag=true;mb.classList.add('drag');sx=e.clientX;sy=e.clientY;spx=panX;spy=panY;mb.setPointerCapture(e.pointerId)});mb.addEventListener('pointermove',e=>{if(!drag)return;panX=spx+e.clientX-sx;panY=spy+e.clientY-sy;applyView()});mb.addEventListener('pointerup',()=>{drag=false;mb.classList.remove('drag')});window.addEventListener('resize',resetView)}
bind();clock();setInterval(clock,1000);load();setInterval(load,12000);setTimeout(resetView,120);
